force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <label>QWD Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QWD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/DisplayMode__c.field-meta.xml
<CustomField>
    <fullName>DisplayMode__c</fullName>
    <label>Display Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DesignMode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/InitApexName__c.field-meta.xml
<CustomField>
    <fullName>InitApexName__c</fullName>
    <label>Init Apex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/IsCUDActions__c.field-meta.xml
<CustomField>
    <fullName>IsCUDActions__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do you need to display standard actions (create, edit, delete) based on user&apos;s permission?</inlineHelpText>
    <label>Is CUD Actions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/IsInlineEdit__c.field-meta.xml
<CustomField>
    <fullName>IsInlineEdit__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is it possible to edit data directly in the datatable?</inlineHelpText>
    <label>Is Inline Edit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/IsLazyDataLoad__c.field-meta.xml
<CustomField>
    <fullName>IsLazyDataLoad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lazy Data Load</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/PostActionApexName__c.field-meta.xml
<CustomField>
    <fullName>PostActionApexName__c</fullName>
    <label>Post-Action Apex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <inlineHelpText>In the case the SObject Type is filled (for example, Case), the data can only be of this type. Otherwise, the data can be any, defined in the Init Apex Class.</inlineHelpText>
    <label>SObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/DesignMode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Light</fullName>
        <default>true</default>
        <label>Light</label>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <description>Quick Web Datatable.
Display type/design of elements.</description>
    <masterLabel>QWD Design Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuickSelector.cls
global without sharing class QuickSelector {
    global static List<Configuration__c> getAllQuickConfigurations() {
        return [
            SELECT Id, Name, InitApexName__c, IsCUDActions__c, DisplayMode__c,
                IsInlineEdit__c, IsLazyDataLoad__c, SObjectType__c, PostActionApexName__c
            FROM Configuration__c
        ];
    }

    global static Configuration__c getConfigurationRecordByName(String name) {
        Configuration__c config = [
            SELECT Id, Name, InitApexName__c, IsCUDActions__c, DisplayMode__c,
                IsInlineEdit__c, IsLazyDataLoad__c, SObjectType__c, PostActionApexName__c
            FROM Configuration__c
            WHERE Name = :name
            LIMIT 1
        ];

        return config;
    }
}